version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.6"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  jobs:
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
    pre_build:
      - echo "Command run at 'pre_build' step"
      - cd docs && mkdir build/ && mkdir -p source/api/
      - cd docs && pwd && ls && sphinx-apidoc --module-first -o source/api/ ../easycv/
    post_build:
      - echo "Command run at 'post_build' step"
      - cd docs && cp -r ../configs  build/
      - cd docs && mkdir -p build/benchmarks/ && cp  -r ../benchmarks/selfsup  build/benchmarks/

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
formats: all

python:
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/runtime.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
