version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.6"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  jobs:
    post_create_environment:
      - pip install opencv-python
    pre_build:
      - echo "Command run at 'pre_build' step"
      - pip install torch==1.10.0+cu102 torchvision==0.11.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html
      - pip install mmcv-full==1.4.1 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.10.0/index.html

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
formats: all

python:
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/runtime.txt
    # - method: pip
    #   path: .
    #   extra_requirements:
    #     - opencv-python
