version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  jobs:
    post_checkout:
      - cat requirements/runtime.txt | grep -v opencv-python-headless > a.txt && mv a.txt requirements/runtime.txt
    post_install:
      - cd docs && rm -rf source/api/ && sphinx-apidoc --module-first -o source/api/ ../easycv/
  #   pre_build:
  #     - echo "Command run at 'pre_build' step"
  #     - pip install torch==1.10.0 torchvision==0.11.0
  #     - pip install mmcv==1.4.1

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
formats: all

python:
  install:
    - requirements: requirements/docs.txt
    - requirements: requirements/readthedocs.txt
    - requirements: requirements/runtime.txt
