name: Lint test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install pre-commit hook
        run: |
          pip install pre-commit
          cp .github/hooks/pre-commit .git/hooks/
      - name: Linting
        run: pre-commit run --all-files
